dat_em<-readRDS("summarySCC_PM25.rds")
scc<-readRDS("Source_Classification_Code.rds")
dbc<-subset(dat_em,dat_em$fips=="24510"|dat_em$fips=="06037"&dat_em$type=="ON-ROAD")
ybc<-aggregate(dbc$Emissions,by=list(dbc$fips,dbc$year),FUN=sum)
colnames(ybc)<-c("city","year","emissions")
library(ggplot2)
png(filename="plot6.png")
qplot(year,emissions,data=ybc,color=city,geom="line")+ggtitle("PM2.5 Emissions in LA County and Baltimore City")+ylab("Motor Vehicle Emissions(Tons)")+xlab("Year") 
dev.off()