dat_em<-readRDS("summarySCC_PM25.rds")
scc<-readRDS("Source_Classification_Code.rds")
dat_b<-subset(dat_em,dat_em$fips=="24510")
dat_b_y<-aggregate(dat_b$Emissions,by=list(dat_b$type,dat_b$year),FUN=sum)
colnames(dat_b_y)<-c("type","year","emissions")
library(ggplot2)
png(filename="plot3.png")
qplot(year,emissions,data=dat_b_y,color=type,geom="line")+ggtitle("Emissions of PM2.5 by pollutant type")+ylab("Total Emissions (tons)")+xlab("Year") 
dev.off()